### PR TITLE
Avoid deploying all pods at the same time

### PR DESCRIPTION
**Pull request by vdel**
Improve stability of the cluster

### CODE REVIEW

**Comment by thomas-riccardi** [comment]
Hugo proposes to use gevent with a controlled pool size to avoid waves of start & wait in chunks and have instead a constant number of in flight jobs:
```
from gevent.monkey import patch_all
patch_all()
from gevent.pool import Pool
import time
import random


def deploy_worker_nn(i):
    print "deploying worker n %s" % i
    sleep_time = random.uniform(0.5, 2.0)
    time.sleep(sleep_time)  # worker takes between 0.5s and 2.0 to deploy


pool = Pool(10)

for i in range(10000):
    pool.spawn(deploy_worker_nn, i)  # will block if pool is full


pool.join()
```
caveats: 
- monkey patching need to be done early in the python process life
- gevent + kubernetes client to test

**Comment by maingoh** [comment]
According to the requirements, it's just a REST client that uses requests so I am confident it will work with gevent.

**Comment by vdel** [comment]
That's completely overkill no ?
I would use gevent very carefully and the least possible

**Comment by maingoh** [comment]
A threadpool would also work. I didn't know exactly what it was for but thomas asked for something in python that control the maximum of concurrent tasks

**Comment by thomas-riccardi** [comment]
it is indeed probably overkill; I wanted to avoid: {update N; wait N;} loop
and have alwas N updating, it's faster; but it's clearly not a priority.

**Comment by vdel** [comment]
Up on this: it's actually an important fix that avoids apocalypse when deploying worker-nn

**Pull request merged**
